GET http://localhost:3000/feature/public

### private
GET http://localhost:3000/feature/private
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxQGFjbWUuY29tIiwiaWF0IjoxNzE3ODgyODI2LCJleHAiOjE3MTc4ODI4ODZ9.skYapz2I6pxl8F4G0fTEXDWKG5HO-vDXWaKeUHjcTOM